service: python3-lambda

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-southeast-2
  memorySize: 2056

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: /
          method: any
          cors: true

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
  # https://github.com/UnitedIncome/serverless-python-requirements
  pythonRequirements:
    # Docker must be installed on Windows/Mac:
    # https://serverless.com/blog/serverless-python-packaging/
    dockerizePip: non-linux
    # Reduces package size by removing directories like `PyCache`.
    # Do not use this option on win32 systems.
    # slim: true
    # strip: false